### ISSUE TITLE
"An error occurred" (TypeError: must be type, not classobj)

### ISSUE THREAD

**Issue by stuartlangridge** [JarbasAl/skill-youtube-play#3]
After "hey mycroft, play portishead on youtube", Mycroft says there was an error, and the below is written to `/var/log/mycroft-skills.log`:

```
13:22:52.031 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Youtube Skill
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mycroft_core-18.2.2-py2.7.egg/mycroft/skills/core.py", line 598, in wrapper
    handler(message)
  File "/opt/mycroft/skills/skill-youtube-play/audio_skill.py", line 165, in adapt_handler
    handler(message)
  File "/opt/mycroft/skills/skill-youtube-play/__init__.py", line 40, in handle_play_song_intent
    self.youtube_play(title)
  File "/opt/mycroft/skills/skill-youtube-play/__init__.py", line 72, in youtube_play
    self.audio.play(videos)
  File "/opt/mycroft/skills/skill-youtube-play/audio_skill.py", line 29, in play
    super(AudioServiceB, self).play(tracks, utterance)
TypeError: must be type, not classobj
```

**Comment by JarbasAl** [comment]
https://github.com/MycroftAI/mycroft-core/pull/1502   should fix it
